# Problems

## Problem 1

Find the currents going through R2 and R4 in the following circuit
<center><img src="circuit1.png" width="500" /></center>

**Solution**
<center><img src="circuit1_ans.jpg" width="500" /></center>

Mesh equations:
$$
\begin{array}{l}
\left(2 I_{1}+2 I_{3}\right)+\left(8 I_{1}+8 I_{2}\right)=40 \\
\left(8 I_{2}+8 I_{1}\right)+\left(6 I_{2}\right)+\left(6 I_{2}-6 I_{3}\right)=0 \\
\left(2 I_{3}+2 I_{1}\right)+\left(6 I_{3}-6 I_{2}\right)+\left(2 I_{3}\right)+\left(3 I_{3}\right)=20
\end{array}
$$
Hence,
$$
\begin{array}{l}
10 I_{1}+8 I_{2}+2 I_{3}=40 \\
8 I_{1}+20 I_{2}-6 I_{3}=0 \\
2 I_{1}-6 I_{2}+13 I_{3}=20
\end{array}
$$
which leads to,
$$
I_{1}=6,34 \mathrm{A}, I_{2}=-2,75 \mathrm{A}, I_{3}=-0,71 \mathrm{A}
$$
Finally
$$
I_{R2}=I_{1}+I_{3}=5,63 \mathrm{A}\\
I_{R4}=I_{3}-I_{2}=2,04 \mathrm{A}
$$

In [2]:
from numpy.linalg import solve

In [5]:
A=np.matrix('10,8,2;8,20,-6;2,-6,13')
b=np.matrix('40;0;20')
x=solve(A,b)
print(x)

[[ 6.33802817]
 [-2.74647887]
 [-0.70422535]]


In [2]:
A=np.matrix('10,-8,-2;-8,20,-6;-2,-6,13')
b=np.matrix('40;0;-20')
x=solve(A,b)
print(x)

[[6.33802817]
 [2.74647887]
 [0.70422535]]


In [4]:

A=np.matrix('6,-2;-2,8')
b=np.matrix('12;-1.8')
x=solve(A,b)
print(x)

[[2.1]
 [0.3]]


In [5]:
6.6/26

0.25384615384615383

In [4]:
 (6.33802817-0.70422535)*2+(6.33802817-2.74647887)*8

40.00000004

## Problem 2

Find the current going through R4 in the following circuit
<center><img src="circuit2_.png" width="500" /></center>

**Solution**
<center><img src="circuit2_ans.jpg" width="500" /></center>

Mesh equations
$$
\begin{array}{l}
\left(1 I_{1}\right)+\left(2 I_{1}+2 I_{2}\right)=20 \\
\left(2 I_{2}+2 I_{1}\right)+\left(1 I_{2}\right)+\left(1 I_{2}-1 I_{3}\right)=0\\
I_3=2mA
\end{array}
$$
Then,

$$
\begin{array}{l}
3 I_{1}+2 I_{2}=20 \\
2 I_{1}+4 I_{2}-I_{3}=0 \\
I_{3}=2
\end{array}
$$
The solution to the system of equations is,
$$
I_{1}=9,5 \mathrm{mA}, I_{2}=-4,25 \mathrm{mA}, I_{3}=2 \mathrm{mA}
$$
Then
$$I_{R4}=I_3-I_2=6,25\mathrm{mA}$$

In [7]:
A=np.matrix('3,2,0;2,4,-1;0,0,1')
b=np.matrix('20;0;2')
x=solve(A,b)
print(x)

[[ 9.5 ]
 [-4.25]
 [ 2.  ]]


## Problem 3

Find the current and voltage drop in through R4 in the following circuit. How many nodes are there?
<center><img src="circuit3.png" width="500" /></center>

**Solution**

Let's apply mesh analysis for the three lower meshes and the outer loop, assuming they are all clockwise. The equations are:

$$
\begin{array}{l}
I_1(40+15)+I_2(-15)=15 \\
I_2=0.1\\
I_2(-10)+I_3(20)+I_4(10)=0 \\
I_2(4)+I_3(10)+I_4(20+10+4)=15 \\
\end{array}
$$

In [3]:
A=np.matrix('55,-15,0,0;0,1,0,0;0,-10,20,10;0,4,10,34')
b=np.matrix('15;0.1;0;15')
x=solve(A,b)
print(x)

[[ 0.3       ]
 [ 0.1       ]
 [-0.19310345]
 [ 0.4862069 ]]


$I_{R4}=I_3+I_4=0.29A$

$\Delta V_{R4}=I_{R4}R_4=0.29\times10=2.9V$

*Alternative solution*: Let's combine R3 and R4 as they are in parallel, so $R_{eq}=(R_3R_4)/(R_3+R_4)=100/20=5\Omega$. It is not required, but we simplify the analysis as we now require 3 equations instead of 4. Now there are only 3 meshes.Using the outer loop instead of mesh 3

$$
\begin{array}{l}
I_1(40+15)+I_2(-15)+I_3(0)=15 \\
I_2=0.1\\
I_2(5+4)+I_3(20+5+4)=15
\end{array}
$$

In [13]:
A=np.matrix('55,-15,-40;0,1,0;0,9,29')
b=np.matrix('15;0.1;15')
x=solve(A,b)
print(x)

[[0.65360502]
 [0.1       ]
 [0.4862069 ]]


The net current is going though $R_4$ is then $I_{R_4}=(I_2+I_3)R_{eq}/R_4=0.29A$, which is the same as our previous result.

## Problem 4

Find the Thevenin's equivalent between A and B
<center><img src="circuit4.png" width="500" /></center>

![](circuit4.png)

**Solution**

To calculate $V_{th}$, let us choose the the two lower meshes and the outer loop, then 
$$
\begin{array}{l}
(40+15) I_{1}-15 I_{2}=17,4 \\
I_{2}=0,1 \\
14 I_{2}+40 I_{3}=17,4
\end{array}
$$
Then
$$
I_{1}=0.34 \mathrm{~A} ; I_{2}=0.1 \mathrm{~A} ; I_{3}=0.4 \mathrm{~A}
$$
Hence
$$
V_{th}=10 \Omega \cdot (0.4+0.1) \mathrm{A}=5V
$$
Now $R_{th}$:
<center><img src="circuit4_ans.png" width="500" /></center>

There is a short circuit for the $40\Omega$ and $15\Omega$ resistors, so they do not contribute. Everything comes down to two resistors in parallel with values $10\Omega$ and $(25+4)\Omega$
$$
R_{th}=\frac{10 \Omega \cdot (26+4) \Omega}{10 \Omega+(26+4) \Omega}=7,5\Omega
$$

In [26]:
A=np.matrix('55,-15,0;0,1,0;0,14,40')
b=np.matrix('17.4;0.1;17.4')
x=solve(A,b)
print(x)

[[0.34363636]
 [0.1       ]
 [0.4       ]]


## Problem 5

Find the Thevenin's equivalent between A and B
<center><img src="circuit5.png" width="500" /></center>

**Answer**

In [11]:
A=np.matrix('22,-20,-20;0,1,0;-20,25,75')
b=np.matrix('40;2;0')
x=solve(A,b)
print(x)

[[4. ]
 [2. ]
 [0.4]]



$$
I_{1}=4 \mathrm{mA} ; I_{2}=2 \mathrm{mA} ; I_{3}=0.4 \mathrm{mA} 
$$
Hence
$$
V_{th}=40k\Omega\cdot I_{3}=16V
$$

In [12]:
40*0.4

16.0

<center><img src="circuit5_ans.png" width="500" /></center>
$R_{th}=11.84k\Omega$

In [11]:
parallel1=20*2/(20+2)
series1=parallel1+10+5
parallel2=(series1)*40/(series1+40)
print(parallel2)

11.84
