# Problems

## Problem 1

A LED is connected to an arduino, which supplies a voltage of 5V.  For a standard LED, the maximum current is usually 20mA. Find the minimum value of the resistance that safely allows to turn on the LED. Assume a built-in potential of $V_{bi}=1.7V$

<center><img src="p1_.png" width="400" /></center>

**Solution**:

We assume the LED to be activated with a current flowing clockwise, so we replace the LED by a voltage source of value $V_{bi}=1.7V$. Applying Kirchoff, we have

$$ IR+1.7=5\implies IR=3.3V \implies R_{min}=3.3V/I_{max}=3.3V/20mA=165\Omega$$

In [1]:
3.3/(20*10**(-3))

165.0

## Problem 2

In the following circuit, calculate the Thevenin's equivalent between A and B, and the current going thorough the diode when the resistance is $R=2k\Omega$ and $R=500\Omega$
<center><img src="p2.png" width="500" /></center>

**Solution**

As for the Thevenin's resistance, the resistor of value $R$ and $2k$ are in parallel, and the equivalent of these is in series with the $1k$ resistor. Hence,

<center><img src="p2s.png" width="500" /></center>
$$
R_{T h}=\frac{2 R}{2+R}+1(\mathrm{k} \Omega)
$$

Using mesh analysis, with the left mesh clockwise and the central mesh counterclockwise (the right mesh does not conduct any current due to short circuit)

$$
\begin{aligned}
I_{1} &=5 \mathrm{~mA} \\
5 &=R\left(I_{1}+I_{2}\right)+2 I_{2}
\end{aligned}
$$

The current $I_2$ is then,
$$
I_{2}=\frac{5(1-R)}{R+2} \mathrm{mA}
$$
Finally, the Thevenin's voltage can be calculated as
$$
V_{AB}=V_{th}=-2 I_{2}=\frac{10(1-R)}{R+2}  \mathrm{V}
$$

If we now substitute the values of $R$ given,

$R=2k\Omega \implies V_{th}=2.5V,R_{th}=2k\Omega$,
and $R=500\Omega \implies V_{th}=-2V,R_{th}=1,4k\Omega$

We now apply the simplified circuits to analyze the state of the diode. For the first value, we assume the diode to be forwardly biased. Then, applying Kirchoff 

$$
\begin{array}{l}
2,5=2 I_{D}+0,7 \\
I_{D}=0,9 \mathrm{mA}>0
\end{array}
$$

which is consistent.

For the second value, we assume the diode to be with reverse bias, so 

$$
\begin{aligned}
2 &=-V_{D}+1,4 I_{D} \\
V_{D} &=-2 \mathrm{V}<0,7 \mathrm{V}
\end{aligned}
$$

which is consistent.

## Problem 3

Calculate the reading of the voltmeter when the voltage source is V=10V and V=5V

<center><img src="p7.png" width="500" /></center>

**Solution**:

Let's assume that both diodes are forward biased, and let's employ mesh analysis with clockwise mesh currents.

$$
\begin{array}{l}
(10+15) I_{1}+(-10) I_{2}=10-2.5-0.7 \\
(-10)I_{1}+ (10+5) I_{2}=-10+2.5+0.7 \\
\end{array}
$$

$$
I_{1}=0.12 \mathrm{mA}, I_{2}=-0.37 \mathrm{mA}
$$

This solution is consistent with our hypothesis

In [5]:
import numpy as np
from numpy.linalg import solve
A=np.matrix('25,-10;-10,15')
b=np.matrix('6.8;-6.8')
x=solve(A,b)
print(x)

[[ 0.12363636]
 [-0.37090909]]


The voltmeter then measures $V=5I_2+10=-0.37(5)+10=8.145V$

In [6]:
-0.371*5+10

8.145

However, for 5V

$$
\begin{array}{l}
(10+15) I_{1}+(-10) I_{2}=5-2.5-0.7 \\
(-10)I_{1}+ (10+5) I_{2}=-10+2.5+0.7 \\
\end{array}
$$

$$
I_{1}=-0.14 \mathrm{mA}, I_{2}=-0.55 \mathrm{mA}
$$

which is not consistent as $I_1<0$. 

In [6]:
A=np.matrix('25,-10;-10,15')
b=np.matrix('1.8;-6.8')
x=solve(A,b)
print(x)

[[-0.14909091]
 [-0.55272727]]


Let's then assume that diode on the left mesh is reverse biased,so we are only concerned about the right mesh now. The current must be counterclokwise so

$$(10+5) I=10-2.5-0.7\implies I=0.45mA$$

which is consistent because now the voltage between the diode is $V_D=5-(2.5+0.45(10))=-2V<0.7V$.

The voltmeter measures: $V=5I+10=-0.45(5)+10=7.75V$

In [15]:
5-(2.5+0.45*(10))

-2.0

## Problem 4

*Half wave rectifier*: calculate the maximum current that flows through the diode and draw the current as a function of time in the following circuit. The voltage source oscillates as $v(t)=5Vsin(\omega t)$

<center><img src="p4.png" width="400" /></center>

**solution**: 

$$I100-0.7=v(t)\implies I_{max}100-0.7=5\implies I_{max}=43mA$$

The diode allows a current only when the voltage is positive (clockwise current), and when $v(t)>0.7V$.

In [ ]:
import numpy as np
from numpy.linalg import solve
A=np.matrix('20,-10;-10,30')
b=np.matrix('20;-0.7')
x=solve(A,b)
print(x)

## Problem 5

Calculate the maximum current that flows through the diode in the following circuit for $v(t)=20V\cos(wt)$:

<center><img src="p5.png" width="400" /></center>

**Solution**: we assume the diode to be forwardly biased (as we want to calculate the maximum current, it couldn't be otherwise), so we replace it by a voltage of 0.7V. Additionally, the maximum current will happe when the voltage source instantly becomes a 20V, so replace it by a DC voltage source as well.

Applying mesh analysis with clockwise mesh currents:

$$
\begin{array}{l}
(10+10) I_{1}+(-10) I_{2}=20 \\
(-10)I_{1}+ (10+20) I_{2}=-0.7 \\
\end{array}
$$

$$
I_{1}=1.186 \mathrm{mA}, I_{2}=0.372 \mathrm{mA}
$$

$$I_{max}=I_2=0.372mA$$

In [1]:
import numpy as np
from numpy.linalg import solve
A=np.matrix('20,-10;-10,30')
b=np.matrix('20;-0.7')
x=solve(A,b)
print(x)

[[1.186]
 [0.372]]


## Problem

Analyze qualitatively the functioning of the following circuits.

<center><img src="p6.png" width="400" /></center>
<center><img src="protect.png" width="200" /></center>

**Solution**:

The first circuit alternates between the different LEDs: the the current is clockwise only the right LED is one, an the opposite for the left one.

The second circuit indicates how to use a **Flywheel diode** as a protection circuit. When we switch off the switch, the energy stored in the inductor finds a path through the diode to safely dissipate the energy, avoiding voltage spikes (back emf) that could damage other circuit components.

# Problem 7

Find the minimum value of the voltage source so that there is current flowing through the diode.

<center><img src="extra.png" width="400" /></center>

**Solution**:

Let's impose a forward biased to the diode, so

$$
\begin{array}{l}
I_{1}=I_{2}+I_{D} \\
V_{i}=R_{2} I_{1}+R_{1} I_{2} \\
R_{1} I_{2}=0.7
\end{array}
$$

$$
I_{1}=\frac{V_{i}-0.7}{R_{1}}, \quad I_{2}=\frac{0.7}{R_{1}} 
$$

Hence

$$\quad I_{D}=\frac{V_{i}-0.7}{R_{1}}-\frac{0.7}{R_{1}}=\frac{R_{1} \cdot\left(V_{i}-0.7\right)-R_{2} \cdot 0.7}{R_{1} \cdot R_{2}}$$

As we are assuming the diode is forward biased, then $I_D>0$ must be true, which implies

$$
R_{1} \cdot\left(V_{i}-0,7\right)-R_{2} \cdot 0.7 \geq 0
$$

$$
V_{i} \geq \frac{R_{1}+R_{2}}{R_{1}} \cdot 0.7 \mathrm{V}
$$